### ISSUE TITLE
Blockquotes Guides

### ISSUE THREAD

**Issue by threecifanggen** [blueteafrog/logseq-oxfordblue-theme#1]
Hi!
Does there exist a guide about using different blockquote(like tip blockquote, note blockquote)?

**Comment by d5technews** [comment]
Hi, If I understood you correctly. You can use the built in feature to invoke the different admonitions by using `<` I attached a screen cap as an example 

https://user-images.githubusercontent.com/7694090/147600668-9adfacca-1a56-4216-a4b2-65b159ad7351.mov

**Comment by threecifanggen** [comment]
> Hi, If I understood you correctly. You can use the built in feature to invoke the different admonitions by using `<` I attached a screen cap as an example
> 
>  Admonitions.mov

It works. Thanks.

**Comment by ituri** [comment]
You should consider adding the video to your README. I just saw the screenshots of how you implemented the different admonition styles and wondered how to access them. This video, hidden away in the issues, helped me a lot since I didn't know that this was a native logseq feature. 😊

**Comment by d5technews** [comment]
Thanks for the suggestion I'll definitely add it to the next update 😀
