### ISSUE TITLE
Blurry font in code blocks with light theme

### ISSUE THREAD

**Issue by vicrdguez** [blueteafrog/logseq-oxfordblue-theme#4]
Hi!

I've noticed with the latest Logseq update (0.6.6) that code block text in the light theme is not sharp. I've tried to look into it but not sure what the problem might be.

**Light theme**:
![image](https://user-images.githubusercontent.com/52254255/164967836-47ef8bc9-7abf-416b-8a0c-9c4777e1559d.png)

**Dark theme**
![image](https://user-images.githubusercontent.com/52254255/164967864-f03507bb-85d8-4d0f-a1c7-95df543e5200.png)

Probably this is an easy to fix thing but out of my CSS knowledge

**Comment by d5technews** [comment]
Hi sorry it took so long to respond. I'm not sure why I'm not receiving new issue notifications. Thank you for reporting I'll look into it asap.

**Comment by d5technews** [comment]
Should be fixed. Please let me know if you experience any more issues

**Comment by vicrdguez** [comment]
No worries, keep up the good work!
